name: "Run Anchore Scan Action"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        image-reference: "alpine:latest"
        debug: true
